coverage:
  range: 60..90
  round: down
  precision: 2
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
codecov:
  allow_pseudo_compare: False