name: PR

on:
  issues:
    types: [opened, reopened]

env:
  ISSUE_URL: ${{ github.event.issue.url }}
  ISSUE_TITLE: ${{ github.event.issue.title }}
  ISSUE_BODY: ${{ github.event.issue.body }}
jobs:
  new_issue:
    name: New Issue
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Send Issues to slack
      run: |
        echo "${{ github.event.action.number }}"
        echo "Newly opened issue at "
        cd .github/workflows
        chmod a+x send_issue.sh
        ./send_issue.sh ${ISSUE_TITLE} ${ISSUE_BODY} ${ISSUE_URL} ${GITHUB_RUN_ID} ${{ secrets.SLACK_WEBHOOK_URL_DA_ALERTS_SUCCESS }} ${{ secrets.API_TOKEN_TO_GITHUB }}