name: PR

on:
  issues:
    types: [opened,created]
jobs:
  new_issue:
    name: New Issue
    runs-on: ubuntu-latest
    steps:
      - name: Save the PR number in an artifact
        shell: bash
        env:
          PR_NUM: ${{ github.run_id }}
        run: echo $PR_NUM 