name: PR

on:
  issues:
    branches: ['devadv-2257-issue']
jobs:
  new_issue:
    name: New Issue
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.event.action }}"
          echo "Newly opened issue at "
          echo $URL
          echo "Issue number "
          echo $NUMBER
          echo "Author is "
          echo $AUTHOR
          echo "Body of the issue is "
          echo $BODYTEXT