name: PR

on:
  push:
    branches: [ "devadv-2257-issue" ] 
  issues:
    types: [opened]
jobs:
  new_issue:
    name: New Issue
    runs-on: ubuntu-latest
    steps:
      - name: Save the PR number in an artifact
        shell: bash
        env:
          PR_NUM: ${{ github.event.number }}
        run: echo $PR_NUM 