name: PR

on:
  issues:
    branches: [ "devadv-2257-issue" ] 
    types: [opened]

env:
  NUMBER: ${{ github.event.issue.number }}
  URL: ${{ github.event.issue.bodyUrl}}
  AUTHOR: ${{ github.event.issue.author }}
  BODYTEXT: ${{ github.event.issue.bodyText }}
jobs:
  new_issue:
    name: New Issue
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Newly opened issue at "
          echo $URL
          echo "Issue number "
          echo $NUMBER
          echo "Author is "
          echo $AUTHOR
          echo "Body of the issue is "
          echo $BODYTEXT