name: PR

on:
  push:
    branches: ['devadv-2257-issue']
  # issues:
  #   types: [opened, reopened]
jobs:
  new_issue:
    name: New Issue
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.event.action.number }}"
          echo "Newly opened issue at "
          echo "ISSUE_TITLE: ${{ github.event.issue.title }}"
          echo "ISSUE_BODY: ${{ github.event.issue.body }}"
          echo "ISSUE_URL: ${{ github.event.issue.issue_url }}"
          ../.github/workflows/send_issue.sh ${ISSUE_TITLE} ${ISSUE_BODY} ${ISSUE_URL} ${GITHUB_RUN_ID} ${{ secrets.SLACK_WEBHOOK_URL_DA_ALERTS_SUCCESS }} ${{ secrets.API_TOKEN_TO_GITHUB }}