name: PR

on:
  pull_request:
    branches: [master]

jobs:
  build:
    services:
      couchbase:
        image: couchbase/server-sandbox:7.0.0-beta
        ports:
          - 8091-8094:8091-8094
          - 11210:11210

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['12']

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1