name: PR

on:
  pull_request:

jobs:
  build:
    services:
      couchbase:
        image: couchbase/server-sandbox:7.1.3
        ports:
          - 8091-8094:8091-8094
          - 11210:11210

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: ['16']

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
